# Get all todo
GET http://localhost:8080/api/todo
Accept: application/json

###

# Get todo by id
GET http://localhost:8080/api/todo/1
Accept: application/json

###

# Create todo
POST http://localhost:8080/api/todo
Accept: application/json
Content-Type: application/json

{
  "name": "make some text"
}

###

# Update todo
PUT http://localhost:8080/api/todo/1
Accept: application/json
Content-Type: application/json

{
  "name": "make updated text",
  "description": "test description"
}

###

# Delete todo
DELETE http://localhost:8080/api/todo/1
Accept: application/json